export const oneHundredCars: string[] = [
  "Toyota Camry",
  "Honda Accord",
  "Ford Mustang",
  "Chevrolet Silverado",
  "BMW X5",
  "Mercedes-Benz E-Class",
  "Audi A4",
  "Volkswagen Golf",
  "Nissan Altima",
  "Hyundai Sonata",
  "Kia Optima",
  "Subaru Outback",
  "Mazda CX-5",
  "Lexus RX",
  "Volvo XC60",
  "Tesla Model 3",
  "Jeep Wrangler",
  "Dodge Charger",
  "Chrysler 300",
  "GMC Sierra",
  "Ram 1500",
  "Cadillac Escalade",
  "Lincoln Navigator",
  "Acura MDX",
  "Infiniti Q50",
  "Buick Enclave",
  "Porsche 911",
  "Jaguar F-Pace",
  "Land Rover Range Rover",
  "Mini Cooper",
  "Fiat 500",
  "Alfa Romeo Giulia",
  "Mitsubishi Outlander",
  "Genesis G80",
  "Bentley Continental",
  "Rolls-Royce Phantom",
  "Aston Martin DB11",
  "Ferrari 488",
  "Lamborghini Huracán",
  "McLaren 720S",
  "Bugatti Chiron",
  "Maserati Ghibli",
  "Lotus Evora",
  "Smart Fortwo",
  "Suzuki Swift",
  "Peugeot 308",
  "Renault Megane",
  "Citroen C4",
  "Opel Astra",
  "Skoda Octavia",
  "Seat Leon",
  "Dacia Sandero",
  "Lada Vesta",
  "UAZ Patriot",
  "GAZ Volga",
  "BYD Han",
  "Geely Coolray",
  "Great Wall Haval",
  "Chery Tiggo",
  "Changan CS75",
  "Haval Jolion",
  "Zotye T600",
  "Brilliance V5",
  "JAC S7",
  "FAW Bestune",
  "BAIC X55",
  "Dongfeng AX7",
  "Wey VV7",
  "Lynk & Co 01",
  "Hongqi H9",
  "Proton X70",
  "Perodua Myvi",
  "Tata Harrier",
  "Mahindra XUV700",
  "Maruti Suzuki Swift",
  "Hindustan Ambassador",
  "Isuzu D-Max",
  "SsangYong Rexton",
  "Kia Carnival",
  "Hyundai Tucson",
  "Ford Ranger",
  "Toyota Hilux",
  "Mitsubishi L200",
  "Nissan Navara",
  "Volkswagen Amarok",
  "Chevrolet Colorado",
  "GMC Canyon",
  "Jeep Gladiator",
  "Toyota Land Cruiser",
  "Lexus LX",
  "Mercedes-Benz G-Class",
  "Land Rover Defender",
  "Jeep Grand Cherokee",
  "Ford Bronco",
  "Toyota RAV4",
  "Honda CR-V",
  "Subaru Forester",
  "Mazda CX-30",
  "Kia Sportage",
  "Hyundai Santa Fe",
  "Volkswagen Tiguan",
  "Audi Q5",
  "BMW X3",
  "Mercedes-Benz GLC",
  "Volvo XC40",
];
